version: '2'
services:
 app:
  build: ./application
  container_name: imagecompression_app
  ports:
   - "889:889"
  depends_on:
   - db
  network_mode: "host"
 db:
  build: ./database
  container_name: imagecompression_db
  restart: always
  environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  networks:
   frontend:
    ipv4_address: 10.5.0.5
networks:
 frontend:
  driver: bridge
  ipam:
   config:
    - subnet: 10.5.0.0/16
      gateway: 10.5.0.1